#!/bin/sh
license='
Converts CIDR to IPADDRESS
Copyright (C) 2018 z0noxz, <chris@noxz.tech>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
'

do_cidr2ip() {

    # variable declaration
    cidr=$1
    cidr_invert=$((32-cidr))
    mask=$((4294967295 >> cidr_invert << cidr_invert))
    result=""
    base=256
    i=0

    # base convert decimal mask to base-256
    while [ "$mask" -ne 0 ]; do
        result=$(printf '%-4s%s' $((mask % base)) "$result")
        mask=$((mask / base))
    done

    # output as an ip
    for item in $result; do
        printf '%d' "$item"
        i=$((i+1))
        if [ "$i" -lt 4 ]; then
            printf '.'
        else
            printf '\n'
        fi
    done

    # success
    return 0
}

# check if input is a CIDR, then process it
if [ "$1" -eq "$1" ] 2> /dev/null && [ "$1" -le 32 ] && [ "$1" -gt 0 ]; then
    do_cidr2ip "$1" && exit 0
fi

# if all fails print usage
program_name="${0##*/}"
printf 'Usage: %s CIDR

LICENSE NOTICE
%s
' "$program_name" "$license" >&2

exit 1
