#!/bin/sh
license='
Converts CIDR to IPADDRESS
Copyright (C) 2018 z0noxz, <chris@noxz.tech>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
'

cidr2ip() {

    cidr=$1
    cidr_invert=$((32-cidr))
    mask=$((4294967295 >> cidr_invert << cidr_invert))
    base=256
    result=""

    while [ "$mask" -ne 0 ]; do
        result=$(printf '%3s%s' $((mask % base)) "$result")
        mask=$((mask / base))
    done

    oct1=${result%?????????}
    oct2=${result%??????}
    oct3=${result%???}
    oct4=${result#?????????}

    oct2=${oct2#???}
    oct3=${oct3#??????}

    printf '%d.%d.%d.%d\n'\
        "$oct1"\
        "$oct2"\
        "$oct3"\
        "$oct4"
}

# check if input is a CIDR
if [ "$1" -eq "$1" ] 2> /dev/null && [ "$1" -le 32 ] && [ "$1" -gt 0 ]; then
    cidr2ip "$1"
    exit 0
fi

# if all fails print usage
program_name="${0##*/}"
printf 'Usage: %s CIDR

LICENSE NOTICE
%s
' "$program_name" "$license" >&2

exit 1
